# Generated by Django 5.2.6 on 2025-11-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_brochuredownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Course Final Exam', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=180, help_text='Exam duration in minutes (default 3 hours)')),
                ('passing_score', models.IntegerField(default=80, help_text='Minimum percentage score to pass')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum number of attempts allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='core.course')),
            ],
            options={
                'verbose_name': 'Course Exam',
                'verbose_name_plural': 'Course Exams',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('is_passed', models.BooleanField(blank=True, help_text='True if score >= passing_score', null=True)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='core.courseaccess')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-started_at'],
                'unique_together': {('course_access', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question')),
                ('option_a', models.CharField(help_text='Option A', max_length=500)),
                ('option_b', models.CharField(help_text='Option B', max_length=500)),
                ('option_c', models.CharField(help_text='Option C', max_length=500)),
                ('option_d', models.CharField(help_text='Option D', max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation shown after exam submission', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.courseexam')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('', 'Not answered')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examquestion')),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
