# Generated by Django 5.2.8 on 2025-11-19 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_courseexam_examattempt_examquestion_examanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='ready_for_exam',
            field=models.BooleanField(default=False, help_text='Set when user has played all course videos at least once'),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='ready_for_exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VideoPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('course_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='core.coursescheduleitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Play',
                'verbose_name_plural': 'Video Plays',
                'unique_together': {('user', 'course_item')},
            },
        ),
    ]
