# Generated by Django 5.2.8 on 2025-11-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_courseprogress_ready_for_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='has_violations',
            field=models.BooleanField(default=False, help_text='True if any violations were detected'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='violation_count',
            field=models.IntegerField(default=0, help_text='Total number of violations recorded'),
        ),
        migrations.CreateModel(
            name='ExamViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('right_click', 'Right-Click Attempted'), ('copy_paste', 'Copy/Paste Attempted'), ('dev_tools', 'Developer Tools Opened'), ('tab_switch', 'Tab/Window Switch'), ('back_button', 'Back Button Navigation'), ('fullscreen_exit', 'Fullscreen Exited'), ('other', 'Other Violation')], max_length=20)),
                ('violation_count', models.PositiveIntegerField(default=1, help_text='Number of times this violation occurred')),
                ('description', models.TextField(blank=True, help_text='Additional details about the violation')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('auto_submitted', models.BooleanField(default=False, help_text='True if exam was auto-submitted due to this violation')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.examattempt')),
            ],
            options={
                'verbose_name': 'Exam Violation',
                'verbose_name_plural': 'Exam Violations',
                'ordering': ['-recorded_at'],
                'unique_together': {('attempt', 'violation_type')},
            },
        ),
    ]
