# Generated by Django 5.2.6 on 2025-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_examattempt_has_violations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='duration_minutes',
            field=models.IntegerField(default=150, help_text='Duration in minutes for this attempt (snapshot at creation time)'),
        ),
    ]
